/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yuuitanabe.pipres.web;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class BMP180Web {
	public static void main(String[] args) {
		SpringApplication.run(BMP180Web.class, args);
	}
}