package com.yuuitanabe.webbrowser;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.jsoup.Jsoup;

public class Parsing {
    public static void parsing() {
    	
    }
}
