package com.yuuitanabe.webbrowser;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

class Parsing {
    private Parsing() {
    	throw new IllegalStateException("Parsing class");
    }
	public static void parsing() {
        // TODO Decide how to parse the HTML.
    }
}
