version: 2
jobs:
  build:
    docker:
      - image: archlinux/base

    steps:
      - run:
          name: Update System & Install Tools & Checkout
          command: | 
            pacman -Syu --noconfirm
            pacman -Sy --noconfirm openjdk git openssh
      - checkout 
      
      - run:
          name: CI Build
          command: |
           ./gradlew bootJar
           ./gradlew sonarqube \
           -Dsonar.projectKey=yuui-tanabe_myownbrowser \
           -Dsonar.organization=yuui-tanabe-github \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Deploy
          command: curl -T build/libs/pipres.jar -uyuui-tanabe:$BINTRAY_TOKEN https://api.bintray.com/content/yuui-tanabe/pipres/java/1.0.0/pipres.jar
          when: success
          
