version: 2
jobs:
  prepare:
    docker:
      - image: archlinux/base

    steps:
      - run:
          name: Update System & Install Tools & Checkout
          command: | 
            pacman -Syu --noconfirm
            pacman -Sy --noconfirm openjdk git openssh
      - checkout 
  build:
    docker:
      - image: arhclinux/base
    steps:
      - run:
          name: CI Build
          command: |
           ./gradlew bootJar
           ./gradlew sonarqube \
           -Dsonar.projectKey=yuui-tanabe_myownbrowser \
           -Dsonar.organization=yuui-tanabe-github \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
  deploy:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: Deploy
          command: |
            pacman -Sy curl
            curl -T build/libs/pipres.jar -uyuui-tanabe:$BINTRAY_TOKEN https://api.bintray.com/content/yuui-tanabe/pipres/java/0.0.0/pipres.jar
  workflows:
    version: 2
    jobs:
      - deploy:
        requires:
          - build
      - build:
        requires:
          - prepare
          
