version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic

    steps:
      - run:
          name: Update System & Install Tools
          command: | 
            apt-get update
            apt-get -y upgrade
            apt-get install -y libasound
            dpkg -i jdk-11.0.2_linux-x64_bin.deb
      - checkout
      
      - run:
          name: CI Build
          command: |
           ./gradlew build
            
