version: 2
jobs:
  build:
    docker:
      - image: gentoo/stage3-amd64

    steps:
      - run:
          name: Update System & Install Tools
          command: | 
            apt update
            apt upgrade
            curl -LO -b "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/jdk-11.0.2_linux-x64_bin.deb
            dpkg -i jdk-11.0.2_linux-x64_bin.deb
      - checkout
      
      - run:
          name: CI Build
          command: |
           ./gradlew build
            
