version: 2
jobs:
  Save code to cache:
    docker:
      - image: archlinux/base

    steps:
      - run:
          name: Install Tools
          command: |
            pacman -Syu --noprogressbar --noconfirm
            pacman -Sy --noconfirm --noprogress git openssh tar
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  Build:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: Install Tools
          command: |
            pacman -Syu --noconfirm --noprogress
            pacman -Sy --noconfirm --noprogress tar jdk-openjdk
            source /etc/profile.d/jre.sh
            
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: CI Build
          command: |
           ./gradlew bootJar
           ./gradlew sonarqube \
           -Dsonar.projectKey=yuui-tanabe_myownbrowser \
           -Dsonar.organization=yuui-tanabe-github \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
    
  Deploy:
    docker:
      - image: archlinux/base
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploying
          command: |
            pacman -Sy --noconfirm --noconfirm curl
            curl -T build/libs/pipres.jar -uyuui-tanabe:$BINTRAY_TOKEN https://api.bintray.com/content/yuui-tanabe/pipres/java/0.0.0/pipres.jar
workflows:
  version: 2
  ci-work:
    jobs:
      - Save code to cache
      - Build:
          requires:
            - Save code to cache
      - Deploy:
          requires:
            - Build
        
          
