version: 2
jobs:
  build:
    docker:
      - image: archlinux/base

    steps:
      - run:
          name: Update System & Install Tools & Checkout
          command: | 
            pacman -Syu --noconfirm --noprogressbar
            pacman -Sy --noconfirm --noprogressbar jdk-openjdk git openssh
      - checkout
      - run:
          name: CI Build
          command: |
           ./gradlew bootJar
           ./gradlew sonarqube \
           -Dsonar.projectKey=yuui-tanabe_myownbrowser \
           -Dsonar.organization=yuui-tanabe-github \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
       - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
          environment:
            JAVA_HOME: /usr/lib/jvm/default/bin
  
  deploy:
    docker:
      - image: archlinux/base
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy
          command: |
            pacman -Sy --noconfirm --noconfirm curl
            curl -T build/libs/pipres.jar -uyuui-tanabe:$BINTRAY_TOKEN https://api.bintray.com/content/yuui-tanabe/pipres/java/0.0.0/pipres.jar
workflows:
  version: 2
  ci-work:
    jobs:
      - build
      - deploy:
          requires:
            - build
        
          
