version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic

    steps:
      - run:
          name: Update System & Install Tools & Checkout
          command: | 
            apt-get update
            apt-get install -y curl
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get -y upgrade
            apt-get install -y libasound2 git-lfs
            
      - checkout
      - run: git lfs pull
      - run:
          name: Install Java
          command: dpkg -i jdk*
      
      - run:
          name: CI Build
          command: |
           ./gradlew build
            
