version: 2
jobs:
  build:
    docker:
      - image: archlinux/base

    steps:
      - run:
          name: Update System & Install Tools & Checkout
          command: | 
            pacman -Syu
            pacman -Sy openjdk git openssh
      - checkout
      
      - run:
          name: CI Build
          command: |
           ./gradlew sonarqube \
           -Dsonar.projectKey=yuui-tanabe_myownbrowser \
           -Dsonar.organization=yuui-tanabe-github \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
            
