/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yuuitanabe.pipres;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.boot.autoconfigure.security.oauth2.client.EnableOAuth2Sso;

@SpringBootApplication
@EnableOAuth2Sso
public class I2CAPI extends WebSecurityConfigurerAdapter {
	public static void main(String[] args) {
		SpringApplication.run(OwnController.class, args);
	}
}