/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

import com.yuuitanabe.webbrowser.Parsing;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue(Parsing.get(null));
    }
}
